/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;
/**
 *
 * @author Acer
 */
public class Play extends javax.swing.JFrame {
    /**
     * Creates new form Play
     * @param words
     */ 
       
    public Play() {
        initComponents();    
        ;
        
    }
    private static String w = Game.getWord();    
    private static int c ;
   
    public static String text;
    
    private static char[] b = new  char[(16)];  
    private String u;   
   
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor=
     */  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Guess = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField(1);
        jTextField3 = new javax.swing.JTextField(1);
        jTextField4 = new javax.swing.JTextField(1);
        jTextField5 = new javax.swing.JTextField(1);
        jTextField6 = new javax.swing.JTextField(1);
        jTextField7 = new javax.swing.JTextField(1);
        jTextField8 = new javax.swing.JTextField(1);
        jTextField9 = new javax.swing.JTextField(1);
        jTextField10 = new javax.swing.JTextField(1);
        jTextField11 = new javax.swing.JTextField(1);
        jTextField12 = new javax.swing.JTextField(1);
        jTextField13 = new javax.swing.JTextField(1);
        jTextField14 = new javax.swing.JTextField(1);
        jTextField15 = new javax.swing.JTextField(1);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chancebx = new javax.swing.JLabel();
        us = new javax.swing.JTextField(1);
        jTextField1 = new javax.swing.JTextField(1);

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/download.png"))); // NOI18N

        Title.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        Title.setText("HangMan");

        Guess.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Guess.setText("Enter your guess letter:");

        Submit.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        if(w.length()<2){
            jTextField2.setBackground(new java.awt.Color(240, 240, 240));
            jTextField2.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField2.setBackground(new java.awt.Color(255, 255, 255));
            jTextField2.setText("_");
        }
        jTextField2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.setDisabledTextColor(new java.awt.Color(240, 240, 240));

        jTextField3.setEditable(false);
        if(w.length()<3){
            jTextField3.setBackground(new java.awt.Color(240, 240, 240));
            jTextField3.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField3.setBackground(new java.awt.Color(255, 255, 255));
            jTextField3.setText("_");
        }
        jTextField3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.setDisabledTextColor(new java.awt.Color(240, 240, 240));

        jTextField4.setEditable(false);
        if(w.length()<4){
            jTextField4.setBackground(new java.awt.Color(240, 240, 240));
            jTextField4.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField4.setBackground(new java.awt.Color(255, 255, 255));
            jTextField4.setText("_");
        }
        jTextField4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(null);
        jTextField4.setDisabledTextColor(new java.awt.Color(240, 240, 240));

        jTextField5.setEditable(false);
        if(w.length()<5){
            jTextField5.setBackground(new java.awt.Color(240, 240, 240));jTextField1.setForeground(new java.awt.Color(240, 240, 240));
            jTextField5.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField5.setBackground(new java.awt.Color(255, 255, 255));
            jTextField5.setText("_");
        }
        jTextField5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(null);
        jTextField5.setDisabledTextColor(new java.awt.Color(240, 240, 240));

        jTextField6.setEditable(false);
        if(w.length()<6){
            jTextField6.setBackground(new java.awt.Color(240, 240, 240));
            jTextField6.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField6.setBackground(new java.awt.Color(255, 255, 255));
            jTextField6.setText("_");
        }
        jTextField6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(null);
        jTextField6.setDisabledTextColor(new java.awt.Color(240, 240, 240));

        jTextField7.setEditable(false);
        if(w.length()<7){
            jTextField7.setBackground(new java.awt.Color(240, 240, 240));
            jTextField7.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField7.setBackground(new java.awt.Color(255, 255, 255));
            jTextField7.setText("_");
        }
        jTextField7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(null);
        jTextField7.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });

        jTextField8.setEditable(false);
        if(w.length()<8){
            jTextField8.setBackground(new java.awt.Color(240, 240, 240));
            jTextField8.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField8.setBackground(new java.awt.Color(255, 255, 255));
            jTextField8.setText("_");
        }
        jTextField8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setBorder(null);
        jTextField8.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });

        jTextField9.setEditable(false);
        if(w.length()<9){
            jTextField9.setBackground(new java.awt.Color(240, 240, 240));
            jTextField9.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField9.setBackground(new java.awt.Color(255, 255, 255));
            jTextField9.setText("_");
        }
        jTextField9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(null);
        jTextField9.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });

        jTextField10.setEditable(false);
        if(w.length()<10){
            jTextField10.setBackground(new java.awt.Color(240, 240, 240));
            jTextField10.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField10.setBackground(new java.awt.Color(255, 255, 255));
            jTextField10.setText("_");
        }
        jTextField10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setBorder(null);
        jTextField10.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });

        jTextField11.setEditable(false);
        if(w.length()<11){
            jTextField11.setBackground(new java.awt.Color(240, 240, 240));
            jTextField11.setForeground(new java.awt.Color(240, 240, 240));
        }
        else{
            jTextField11.setBackground(new java.awt.Color(255, 255, 255));
            jTextField11.setText("_");
        }
        jTextField11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setBorder(null);
        jTextField11.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });

        jTextField12.setEditable(false);
        if(w.length()<12){
            jTextField12.setBackground(new java.awt.Color(240, 240, 240));
            jTextField12.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField12.setBackground(new java.awt.Color(255, 255, 255));
            jTextField12.setText("_");
        }
        jTextField12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setBorder(null);
        jTextField12.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });

        jTextField13.setEditable(false);
        if(w.length()<13){
            jTextField13.setBackground(new java.awt.Color(240, 240, 240));
            jTextField13.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField13.setBackground(new java.awt.Color(255, 255, 255));
            jTextField13.setText("_");
        }
        jTextField13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setBorder(null);
        jTextField13.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField13MouseClicked(evt);
            }
        });

        jTextField14.setEditable(false);
        if(w.length()<14){
            jTextField14.setBackground(new java.awt.Color(240, 240, 240));
            jTextField14.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField14.setBackground(new java.awt.Color(255, 255, 255));
            jTextField14.setText("_");
        }
        jTextField14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setBorder(null);
        jTextField14.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField14MouseClicked(evt);
            }
        });

        jTextField15.setEditable(false);
        if(w.length()<15){
            jTextField15.setBackground(new java.awt.Color(240, 240, 240));
            jTextField15.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField15.setBackground(new java.awt.Color(255, 255, 255));
            jTextField15.setText("_");
        }
        jTextField15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setBorder(null);
        jTextField15.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextField15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField15MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Chances Left");

        chancebx.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        chancebx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chancebx.setText(Integer.toString(10));

        jTextField1.setEditable(false);
        if(w.length() < 1){
            jTextField1.setBackground(new java.awt.Color(240, 240, 240));
            jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        }
        else
        us.setBackground(new java.awt.Color(255, 255, 255));
        us.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        us.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        us.setText("_");
        us.setBorder(null);
        us.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        us.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usMouseClicked(evt);
            }
        });
        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        if(w.length() < 1){
            jTextField1.setBackground(new java.awt.Color(240, 240, 240));
            jTextField1.setForeground(new java.awt.Color(240, 240, 240));}
        else{
            jTextField1.setBackground(new java.awt.Color(255, 255, 255));
            jTextField1.setText("_");
        }
        jTextField1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.setDisabledTextColor(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(273, 273, 273))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Guess)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(Title)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chancebx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(227, 227, 227))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chancebx, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Guess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
       String x ="";
      for(int i =0; i<15; i++){
        switch(i) {
            case 0 :
                if(i < w.length())
                b[0] = jTextField1.getText().charAt(0);
            break;
            case 1 :
                if(i < w.length())
                b[1] = jTextField2.getText().charAt(0);
            break;
            case 2 :
                if(i < w.length())
                       b[2] = jTextField3.getText().charAt(0);

            break;
            case 3 :
                if(i < w.length())
                       b[3] = jTextField4.getText().charAt(0);

            break;
            case 4 :
                if(i < w.length())
                       b[4] = jTextField5.getText().charAt(0);

            break;
            case 5 :
                if(i < w.length())
                       b[5] = jTextField6.getText().charAt(0);

            break;            
            case 6 :
                if(i < w.length())
                       b[6] = jTextField7.getText().charAt(0);

            break;
            case 7 :
                if(i < w.length())
                       b[7] = jTextField8.getText().charAt(0);

            break;
            case 8 :
                if(i < w.length())
                       b[8] = jTextField9.getText().charAt(0);

            break;
            case 9 :
                if(i < w.length())
                       b[9] = jTextField10.getText().charAt(0);

            break;
            case 10 :
                if(i < w.length())
                       b[10] = jTextField11.getText().charAt(0);

            break;
            case 11 :
                if(i < w.length())
                       b[11] = jTextField12.getText().charAt(0);

            break;
            case 12 :
                if(i < w.length())
                       b[12] = jTextField13.getText().charAt(0);

            break;
            case 13 :
                if(i < w.length())
                       b[13] = jTextField14.getText().charAt(0);

            break;
            case 14 :
                if(i < w.length())
                       b[14] = jTextField15.getText().charAt(0);

            break;       
       
         default :
            System.out.println("This is impossible.");
        }
      }
       
       
       c = Integer.parseInt(chancebx.getText());
       
         System.out.println("Play class");
         u = us.getText();
         us.setText("_");
         System.out.println(c);
         System.out.println(u);
        user(w,b,u.charAt(0),(c));
        jTextField1.setText(Character.toString(b[0]));
        jTextField2.setText(Character.toString(b[1]));
        jTextField3.setText(Character.toString(b[2]));
        jTextField4.setText(Character.toString(b[3]));
        jTextField5.setText(Character.toString(b[4]));
        jTextField6.setText(Character.toString(b[5]));
        jTextField7.setText(Character.toString(b[6]));
        jTextField8.setText(Character.toString(b[7]));
        jTextField9.setText(Character.toString(b[8]));
        jTextField10.setText(Character.toString(b[9]));
        jTextField11.setText(Character.toString(b[10]));
        jTextField12.setText(Character.toString(b[11]));
        jTextField13.setText(Character.toString(b[12]));
        jTextField14.setText(Character.toString(b[13]));
        jTextField15.setText(Character.toString(b[14]));
        chancebx.setText(Integer.toString(c));
           System.out.println(text);        
    }//GEN-LAST:event_SubmitActionPerformed
    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
       u = us.getText();
    }//GEN-LAST:event_usActionPerformed
    private void jTextField15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField15MouseClicked
        jTextField15.setText("");
    }//GEN-LAST:event_jTextField15MouseClicked
    private void jTextField14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField14MouseClicked
        jTextField14.setText("");
    }//GEN-LAST:event_jTextField14MouseClicked
    private void jTextField13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField13MouseClicked
        jTextField13.setText("");
    }//GEN-LAST:event_jTextField13MouseClicked
    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
        jTextField12.setText("");
    }//GEN-LAST:event_jTextField12MouseClicked
    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
        jTextField11.setText("");
    }//GEN-LAST:event_jTextField11MouseClicked
    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        jTextField10.setText("");
    }//GEN-LAST:event_jTextField10MouseClicked
    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        jTextField9.setText("");
    }//GEN-LAST:event_jTextField9MouseClicked
    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        jTextField8.setText("");
    }//GEN-LAST:event_jTextField8MouseClicked
    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        jTextField7.setText("");
    }//GEN-LAST:event_jTextField7MouseClicked

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked

    }//GEN-LAST:event_SubmitMouseClicked

    private void usMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usMouseClicked
        us.setText("");
    }//GEN-LAST:event_usMouseClicked
   /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oraclevvv.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Guess;
    private static javax.swing.JButton Submit;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel chancebx;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
     
    public static void user( String word, char[] array, char u, int z){
        boolean cond = true;
        int x, y = 0 ;
        x = word.length();
        
        
        int a = c;
        for (int i = 0 ; i <x; i++) {
                             if ((array[i] == '_')) {
                            array[i] = check (u, word.charAt(i));
                     }
                           b[i] = array[i];   
                     }
        if((c-a)>1){
            c = a +1;
        }
                for (int i = 0 ; i < x; i++) { 
                    
                System.out.print(array[i] +" ");
                }  System.out.println("\n");
                
                
            cond = condition(array ,word);
          if (cond = true){
              //Printing the end result
               System.out.println(word);
        System.out.println(u);
        System.out.println(z);
        }
       
    }
    public static char check( char guessletter, char actualletter){
        char a ='_' ;
                                               
        if ( guessletter == actualletter){
             a = actualletter;
            c+=1;
        }
       
        return a;
    }
    public static boolean condition( char[] array,String a){
        String x= "";
        boolean condition = true;
        for (int i = 0; i < a.length(); i++ )
        {
        x = x + array[i] ;
        }
        System.out.println(x.length() +" and "+ a.length()+".");
        
        if (a.equals(x))
        {
            condition = false; 
            text = "Congratulation!!! You won the game.";
            End win = new End(); 
            win.setVisible(true);
            
            System.out.println("\t\t Congratulation!!! You won the game."); 
        }
        else if (c ==0)
        {
             condition = false;
             text = "Sorry. You lost the game";
            End loss = new End(); 
            loss.setVisible(true);
            System.out.println("\t\t Sorry. You lost the game."); 

        }
        else {
            condition = true;
            c -= 1;
            
            
        }
        return condition;
    }
   public static String text(){
           System.out.println(text +"text method");
        return text;
    }
}
